#pragma once

// ÔÂÃ¶¾Ù
enum E_MONTH_TYPE
{
	E_MONTH_TYPE_JAN = 1,
	E_MONTH_TYPE_FEB = 2,
	E_MONTH_TYPE_MAR = 3,
	E_MONTH_TYPE_APR = 4,
	E_MONTH_TYPE_MAY = 5,
	E_MONTH_TYPE_JUN = 6,

	E_MONTH_TYPE_JUL = 7,
	E_MONTH_TYPE_AUG = 8,
	E_MONTH_TYPE_SEP = 9,
	E_MONTH_TYPE_OCT = 10,
	E_MONTH_TYPE_NOV = 11,
	E_MONTH_TYPE_DEC = 12,

};